# Generated by Django 4.2.3 on 2023-07-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
