# Generated by Django 4.2.3 on 2023-07-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
    ]
