# Generated by Django 4.2.3 on 2023-07-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
